# Generated by Django 5.2.11 on 2026-02-22 03:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('task_id', models.AutoField(primary_key=True, serialize=False)),
                ('taskname', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('deadline', models.DateField()),
                ('schedule_type', models.TextField(default='daily')),
                ('interval', models.SmallIntegerField(blank=True, null=True)),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.JSONField(blank=True, null=True)),
                ('delay', models.IntegerField(blank=True, null=True)),
                ('timestamp', models.DateField()),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo.tasks')),
            ],
        ),
    ]
