# Generated by Django 5.2.11 on 2026-02-28 02:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_logs_notes_tasks_previous'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='previous',
            field=models.DateTimeField(default=datetime.datetime(2026, 2, 28, 2, 43, 45, 681221)),
        ),
    ]
