# Generated by Django 5.2.11 on 2026-02-28 03:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_alter_tasks_previous'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='previous',
            field=models.DateTimeField(default=datetime.datetime(2026, 2, 28, 3, 48, 10, 978847)),
        ),
    ]
