# Generated by Django 5.2.11 on 2026-02-28 18:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0026_alter_tasks_previous'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='previous',
            field=models.DateTimeField(default=datetime.datetime(2026, 2, 28, 18, 51, 14, 172327)),
        ),
    ]
