# Generated by Django 5.2.11 on 2026-02-28 20:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0032_remove_tasks_users_alter_tasks_previous'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='previous',
            field=models.DateTimeField(default=datetime.datetime(2026, 2, 28, 20, 5, 41, 83809)),
        ),
    ]
