# Generated by Django 5.2.11 on 2026-03-01 00:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0055_alter_tasks_previous'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='previous',
            field=models.DateTimeField(default=datetime.datetime(2026, 3, 1, 0, 8, 4, 899173)),
        ),
    ]
