# Generated by Django 5.2.11 on 2026-03-06 15:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0114_alter_tasks_previous'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='previous',
            field=models.DateTimeField(default=datetime.datetime(2026, 3, 6, 15, 26, 38, 221456)),
        ),
    ]
