# Generated by Django 5.2.11 on 2026-03-07 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0129_alter_tasks_previous'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='previous',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
