# Generated by Django 5.2.11 on 2026-03-13 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0130_alter_tasks_previous'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='interval',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
