# Generated by Django 5.2.11 on 2026-03-15 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0131_alter_tasks_interval'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='status',
            field=models.TextField(default='active'),
        ),
    ]
